### ISSUE TITLE
data

### ISSUE THREAD

**Issue by itsmengzaime** [blackbbc/NER#1]
where is the data?

**Comment by sarveshsparab** [comment]
@blackbbc 
I am trying to refer to your implementation and I am facing difficulties running your code.
I have notice that you have not uploaded the data in your repository on github. You have gitignored your dev/ and data/ directories.

could you please provide me with the data, if not the entire dataset, only a sample format would also suffice!

Thanks,
Sarvesh

**Comment by blackbbc** [comment]
@sarveshsparab @itsmengzaime 
data uploaded

**Comment by sarveshsparab** [comment]
> @sarveshsparab @itsmengzaime
> data uploaded

Thanks a lot @blackbbc
